### PR TITLE
Move data to data

### LINKED ISSUE #92: Passwords should be stored as data
Passwords should be stored as data

https://github.com/Bambosh/unofficial-homestuck-collection/blob/e84be89aec01c4e48fd7175d1e52cfb4f853960c/src/components/SpecialPages/TzPassword.vue#L65

```html
  },
  methods:{
    // TODO: Passwords should be stored as data
    submitPassword(){
      let url
      switch(this.inputText.toUpperCase()){
ndex 8f7283b..ebc2382 100644
++ b/src/components/UIElements/MediaEmbed.vue
```

826a28728df844bc8913cfcd95621dc979c0b314

### LINKED ISSUE #93: All these flash properties and timings should be s...
All these flash properties and timings should be stored as data

https://github.com/Bambosh/unofficial-homestuck-collection/blob/e84be89aec01c4e48fd7175d1e52cfb4f853960c/src/components/UIElements/MediaEmbed.vue#L18

```html
import Resources from "@/resources.js"

// TODO: All these flash properties and timings should be stored as data
export default {
	props: ['url'],
	data() {
```

89c383c4b7dbb5d099f6bdf59be852ae7e2bd913

### LINKED ISSUE #95: These specific banner designations should be part ...
These specific banner designations should be part of data, not code

https://github.com/Bambosh/unofficial-homestuck-collection/blob/079b40e9c61449d8284e2a9e9aec514331cc61f8/src/components/Page/PageBanner.vue#L26

```html
    // TODO: Banner properties should be set in data, not code
    computed: {
        // TODO: These specific banner designations should be part of data, not code
        banner() {
            let result = undefined
            let num = parseInt(this.page.pageId)
ndex fb0d37f..4b6147b 100644
++ b/src/components/Socials/MagicalJourney.vue
```

0f8b59d06c666a84b8541594c04d92cf81ee57a9

### LINKED ISSUE #118: Rewrite $updateNewReader for datadriven
Rewrite $updateNewReader for datadriven

https://github.com/Bambosh/unofficial-homestuck-collection/blob/4d24b2136ad78d046c183dab3b8deea0a954c0e3/src/main.js#L304

```javascript
      return !(mspaId in this.$archive.mspa.story) || this.$localData.settings.mspaMode ? mspaId : this.$mspaToViz(mspaId).p
    },
    $parseMspaOrViz(userInput, story = 'homestuck') {
      // Takes a user-formatted string and returns a MSPA page number.
      // The output page number may not be real!
      if (this.$localData.settings.mspaMode) {
        return userInput.padStart(6, '0')
      } else {
        return this.$vizToMspa(story, userInput).p
      }
    },
    $updateNewReader(thisPageId, forceOverride = false) {
      // TODO: Rewrite $updateNewReader for datadriven
      let isSetupMode = !this.$archive
      if (!/\D/.test(thisPageId) && '000219' <= thisPageId && thisPageId <= '010030' && (isSetupMode || thisPageId in this.$archive.mspa.story)) {
        let nextLimit

        // Some pages don't directly link to the next page. These are manual exceptions to catch them up to speed
```

1c405035361e03ffdfbf86b1a55937f35d263dd7

### PR DESCRIPTION
**Pull request by GiovanH**
Resolves #92
Resolves #93
Resolves #95
Resolves #118

### CODE REVIEW

File: src/components/Page/PageBanner.vue [hunk 1]
```diff
@@ -1,159 +1,121 @@
...
+      }
+      else if (this.page.theme == 'cascade')
+        return {url: '/images/header_cascade.gif', title: undefined}
+      else if (this.page.theme == 'trickster')
+        return {url: '/images/trickster_sitegraphics/menu.swf', title: undefined}
+      else if (this.page.flag.includes('X2COMBO'))
+        return {url: '/images/act6act5act1x2combo.gif', title: undefined}
+      else if (num == 9987)
+        return {url: '/images/collide_header.gif', title: undefined}
+      else if (num == 10027)
```
Comment (Bambosh) [inline src/components/Page/PageBanner.vue:40]: We could probably switch these out with flags instead of referencing actual page numbers

**Review by Bambosh — APPROVED** [review]
